import Link from "next/link";

export const metadata = {
  title: "Terms of Service — VibeFlow Marketing",
  description: "The terms that govern your use of VibeFlow Marketing.",
};

export default function TermsPage() {
  return (
    <main style={{
      minHeight: "100vh",
      background: "#FFFFFF",
      padding: "80px 24px 120px",
      fontFamily: "var(--font-dm-sans)",
    }}>
      <div style={{ maxWidth: 720, margin: "0 auto" }}>

        <Link href="/" style={{
          fontFamily: "var(--font-dm-sans)", fontSize: 14, fontWeight: 500,
          color: "#05AD98", textDecoration: "none", marginBottom: 32, display: "inline-block",
        }}>← Back to VibeFlow</Link>

        {/* Review banner */}
        <div style={{
          background: "#FFF8E1", border: "1px solid rgba(245,158,11,0.3)",
          borderRadius: 12, padding: "14px 18px", marginBottom: 40,
          fontFamily: "var(--font-dm-sans)", fontSize: 14, color: "#92670A", lineHeight: 1.6,
        }}>
          <strong>Policy under final review.</strong> These Terms are a clear-language summary of how VibeFlow Marketing works. Formal legal copy is being finalized with counsel. Questions? Email <a href="mailto:hello@vibeflow.marketing" style={{ color: "#92670A", textDecoration: "underline" }}>hello@vibeflow.marketing</a>.
        </div>

        <h1 style={{
          fontFamily: "var(--font-syne)", fontWeight: 700,
          fontSize: 36, color: "#1F1F1F", letterSpacing: "-0.02em",
          marginBottom: 8,
        }}>Terms of Service</h1>
        <p style={{ fontFamily: "var(--font-dm-sans)", fontSize: 13, color: "#878787", marginBottom: 4 }}>
          Last updated: April 23, 2026
        </p>
        <p style={{ fontFamily: "var(--font-dm-sans)", fontSize: 13, color: "#878787", marginBottom: 40 }}>
          VibeFlow Marketing is a product of TNTW LLC, a Wyoming limited liability company.
        </p>

        <section style={{ fontSize: 15, color: "#333333", lineHeight: 1.75, marginBottom: 28 }}>
          <h2 style={{ fontFamily: "var(--font-syne)", fontWeight: 700, fontSize: 20, color: "#1F1F1F", marginBottom: 8, marginTop: 24 }}>Plain summary</h2>
          <p style={{ margin: 0, marginBottom: 16 }}>
            VibeFlow Marketing is an AI-powered marketing tool. You give us a prompt and a brand kit; we generate campaign copy, social posts, SEO briefs, and related marketing assets. You own what you generate. We charge a subscription or one-time fee for usage. Don't use the tool to create illegal, abusive, or deceptive content. Don't try to reverse-engineer the service. Be a good human.
          </p>

          <h2 style={{ fontFamily: "var(--font-syne)", fontWeight: 700, fontSize: 20, color: "#1F1F1F", marginBottom: 8, marginTop: 24 }}>Your content</h2>
          <p style={{ margin: 0, marginBottom: 16 }}>
            You own the campaigns, brand kit content, and prompts you create. You're responsible for anything you publish using VibeFlow-generated output. You grant VibeFlow a limited license to store and process that content solely to provide the service to you.
          </p>

          <h2 style={{ fontFamily: "var(--font-syne)", fontWeight: 700, fontSize: 20, color: "#1F1F1F", marginBottom: 8, marginTop: 24 }}>Payment and refunds</h2>
          <p style={{ margin: 0, marginBottom: 16 }}>
            Plans are sold on a prepaid basis. Launch Kit ($49 for 30 days / 100 searches) is a one-time purchase. Annual ($299) is a 12-month recurring subscription you can cancel anytime from the Billing portal. Refund requests within 7 days of purchase will be evaluated case-by-case; contact us.
          </p>

          <h2 style={{ fontFamily: "var(--font-syne)", fontWeight: 700, fontSize: 20, color: "#1F1F1F", marginBottom: 8, marginTop: 24 }}>AI-generated content</h2>
          <p style={{ margin: 0, marginBottom: 16 }}>
            Outputs from the AI agents are generated by third-party language models (currently Anthropic Claude). Outputs may be inaccurate, out-of-date, or unsuitable for your purpose. Review and edit before publishing. VibeFlow doesn't guarantee factual accuracy of any generated content.
          </p>

          <h2 style={{ fontFamily: "var(--font-syne)", fontWeight: 700, fontSize: 20, color: "#1F1F1F", marginBottom: 8, marginTop: 24 }}>Acceptable use</h2>
          <p style={{ margin: 0, marginBottom: 16 }}>
            Don't use VibeFlow to generate content that harasses, defames, infringes copyright, promotes illegal activity, or impersonates a real person. We reserve the right to terminate accounts that violate these norms.
          </p>

          <h2 style={{ fontFamily: "var(--font-syne)", fontWeight: 700, fontSize: 20, color: "#1F1F1F", marginBottom: 8, marginTop: 24 }}>Termination</h2>
          <p style={{ margin: 0, marginBottom: 16 }}>
            You can cancel anytime from the Billing portal. We can suspend or terminate accounts that violate these Terms.
          </p>

          <h2 style={{ fontFamily: "var(--font-syne)", fontWeight: 700, fontSize: 20, color: "#1F1F1F", marginBottom: 8, marginTop: 24 }}>Contact</h2>
          <p style={{ margin: 0, marginBottom: 16 }}>
            Questions about these Terms? <a href="mailto:hello@vibeflow.marketing" style={{ color: "#05AD98" }}>hello@vibeflow.marketing</a>.
          </p>
        </section>

      </div>
    </main>
  );
}
